version: '2.4'
services:
  client:
    build: 
      context: client 
      target: dev
    ports:
      - 3000:3000
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
  server:
    build: 
      context: server 
      target: dev
    ports:
      - 5000:5000
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
  mongo:
    image: mongo
    ports:
    - 27017:27017
    healthcheck:
      test: "[ `echo 'db.runCommand(\"ping\").ok' | mongo localhost/example-database --quiet` ] && echo 0 || echo 1"
      # interval: 5s
      # start_period: 10s
      # timeout: 4s
      # retries: 3
      